### ISSUE TITLE
Firefox version?

### ISSUE THREAD

**Issue by veilm** [amitlevy/needlesearch-client#1]
Is there any chance that there will be a Firefox extension of NeedleSearch in the future?

From what I can tell of https://extensionworkshop.com/documentation/develop/porting-a-google-chrome-extension/, the Firefox WebExtension API is largely identical to that of Chrome, so it would not be much additional work

**Comment by amitlevy** [comment]
I was planning on it, but since NeedleSearch doesn't seem to have gotten traction I'll probably stop working on the project, sorry :/

Appreciate the interest though!
